[package]
name = "fdcom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
clap = "2.33.3"
messages = {path = "../../messages"}
